### ISSUE TITLE
Websites about PulseCaster with mis-directed links

### ISSUE THREAD

**Issue by marwalk** [stickster/pulsecaster#2]
The following websites appear to have links that are not, or no longer, related to the PulseCaster project:

https://fedoraproject.org/wiki/How_to_make_a_podcast
http://stevenrosenberg.net/blog/applications/audio/2015_0306_pulsecaster
https://forum.peppermintos.com/index.php?topic=136.0

**Comment by stickster** [comment]
Hi Mark, unfortunately, I can't do anything about forum or personal blog links. These are frozen in time and are the property of their respective authors. I've updated the Fedora wiki, though. Thanks for sending these links.
