### ISSUE TITLE
Cannot Configure Recording

### ISSUE THREAD

**Issue by jmayekar** [stickster/pulsecaster#3]
I wanted pulse caster to start recording whenever i turned on the computer and Save the recording when i turned off the computer with date and time. 
it should auto save when shutdown is triggered or it should kee saving for 5 min repeat on its own 
Any effort or solution highly appreciated 
Thanks

**Comment by stickster** [comment]
This is an interesting use case, @jmayekar -- thanks for the idea. However, PulseCaster is intended for a specific use case -- helping creators make podcast recordings. A recording of everything coming into your computer's microphone from startup to shutdown is not in scope for this app.

Having said that -- you could use [information from this wiki page](https://fedoraproject.org/wiki/How_to_make_a_podcast) to hack up a script that uses PulseAudio to make such a recording, kicking off on a system that automatically logs in a user when it starts. I hope this helps, and thanks for contributing your idea.
