### ISSUE TITLE
PulseCaster lost my recording

### ISSUE THREAD

**Issue by nekohayo** [stickster/pulsecaster#6]
I have found an unfortunate case where PulseCaster will lose recordings even when you're trying not to:

1. Click Record
2. Click Stop, PulseCaster then prompts you to save
3. Click Cancel (by mistake) in the GtkFileChooser dialog, because you confused it with the filechooser of another application. PulseCaster then tries to stop you from shooting yourself in the foot:
![Screenshot from 2021-04-14 10-49-31](https://user-images.githubusercontent.com/479401/114730763-283ba580-9d0f-11eb-9a6d-694424e9eaba.png)
4. Click "No", because of course you still want to save the recording
5. Try to hit OK (to save) in the remaining GtkFileChooser dialog

Result: clicking the OK button does nothing. The dialog stays there, and the recording is not saved. No tracebacks are shown in the terminal.

**Comment by nekohayo** [comment]
It should also be mentioned that as per old-school HIG, the dialog would benefit from specific button labels instead of Yes/No, so "Throw away my recording" vs "No, I still want to save" would be more user-friendly theoretically speaking, but that's not _extremely_ important thanks to the explanatory label above.

**Comment by cyfive** [comment]
I was fixed this issue in my fork. Can i create pull request to you repo?

**Comment by stickster** [comment]
@cyfive Of course!

**Comment by cyfive** [comment]
@stickster Can you review my PR #9 and send me feedback?
